src/Entity/Task.php
<?php

namespace App\Entity;

use App\Repository\TaskRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Table(name="tasks")
 * @ORM\Entity(repositoryClass=TaskRepository::class)
 */
class Task
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank(message="Please enter a title")
     * @Assert\Regex(
     *     pattern     = "/^[a-zA-Z1-9 ]+$/i",
     *     htmlPattern = "^[a-zA-Z1-9 ]+$",
     *     message = "El campo titulo '{{ value }}' solo puede contener letras y numeros"
     * )
     * @Assert\Length(
     *      min = 2,
     *      max = 50,
     *      minMessage = "Your title  must be at least {{ limit }} characters long",
     *      maxMessage = "Your title  cannot be longer than {{ limit }} characters"
     * )
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @Assert\NotBlank(message="Please enter a content")
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @Assert\NotBlank(message="Please enter nº hours of project")
     * @ORM\Column(type="integer", nullable=true)
     */
    private $hours;

    /**
     * @Assert\NotBlank(message="Please enter the priority")
     * @ORM\Column(type="string", length=25)
     */
    private $priority;

    /**
     * @ORM\Column(type="string", length=3)
     */
    private $completed;

    /**
     * @var DateTime
     * @Assert\NotBlank(message="Please enter the delivery date")
     * @ORM\Column(type="datetime", nullable=false)
     */
    private $delivery_date;

    /**
     * @var DateTime
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @var DateTime|null
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="tasks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * Task constructor.
     */
    public function __construct()
    {
        $this->completed = 'NO';
    }


    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * @param string $title
     * @return $this
     */
    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getContent(): ?string
    {
        return $this->content;
    }

    /**
     * @param string $content
     * @return $this
     */
    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getHours(): ?int
    {
        return $this->hours;
    }

    /**
     * @param int|null $hours
     * @return $this
     */
    public function setHours(?int $hours): self
    {
        $this->hours = $hours;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getPriority(): ?string
    {
        return $this->priority;
    }

    /**
     * @param string $priority
     * @return $this
     */
    public function setPriority(string $priority): self
    {
        $this->priority = $priority;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getCompleted(): ?string
    {
        return $this->completed;
    }

    /**
     * @param string $completed
     * @return $this
     */
    public function setCompleted(string $completed): self
    {
        $this->completed = $completed;

        return $this;
    }

    /**
     * @return DateTimeInterface|null
     */
    public function getDeliveryDate(): ?DateTimeInterface
    {
        return $this->delivery_date;
    }

    /**
     * @param DateTimeInterface|null $delivery_date
     * @return $this
     */
    public function setDeliveryDate(?DateTimeInterface $delivery_date): self
    {
        $this->delivery_date = $delivery_date;

        return $this;
    }

    /**
     * @return DateTimeInterface|null
     */
    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->created_at;
    }

    /**
     * @param DateTimeInterface $created_at
     * @return $this
     */
    public function setCreatedAt(DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return DateTimeInterface|null
     */
    public function getUpdatedAt(): ?DateTimeInterface
    {
        return $this->updated_at;
    }

    /**
     * @param DateTimeInterface|null $updated_at
     * @return $this
     */
    public function setUpdatedAt(?DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return User|null
     */
    public function getUser(): ?User
    {
        return $this->user;
    }

    /**
     * @param User|null $user
     * @return $this
     */
    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Table(name="users")
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Please enter a name")
     * @Assert\Regex(
     *     pattern     = "/^[a-zA-Z ]+$/i",
     *     htmlPattern = "^[a-zA-Z ]+$",
     *     message = "El campo nombre '{{ value }}' solo puede contener letras"
     * )
     * @Assert\Length(
     *      min = 2,
     *      max = 50,
     *      minMessage = "Your first name must be at least {{ limit }} characters long",
     *      maxMessage = "Your first name cannot be longer than {{ limit }} characters"
     * )
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Please enter a surname")
     * @Assert\Regex(
     *     pattern     = "/^[a-zA-Z ]+$/i",
     *     htmlPattern = "^[a-zA-Z ]+$",
     *     message = "El campo nombre '{{ value }}' solo puede contener letras"
     * )
     * @Assert\Length(
     *      min = 2,
     *      max = 50,
     *      minMessage = "Your first name must be at least {{ limit }} characters long",
     *      maxMessage = "Your first name cannot be longer than {{ limit }} characters"
     * )
     */
    private $surname;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank(message="Please enter a email")
     * @Assert\Email(
     *		message = "El email '{{ value }}' no es valido"
     * )
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     *
     */
    private $password;


    /**
     * @var DateTime
     * @ORM\Column(type="datetime")
     * @Assert\Type("\DateTime")
     */
    private $created_at;

    /**
     * @var DateTime
     * @ORM\Column(type="datetime", nullable=true)
     * @Assert\Type("\DateTime")
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity=Task::class, mappedBy="user", orphanRemoval=true)
     */
    private $tasks;

    public function __construct()
    {
        $this->tasks = new ArrayCollection();
        $this->roles = ["ROLE_USER"];
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * @param string $email
     * @return $this
     */
    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param array $roles
     * @return $this
     */
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    /**
     * @param string $password
     * @return $this
     */
    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return $this
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getSurname(): ?string
    {
        return $this->surname;
    }

    /**
     * @param string $surname
     * @return $this
     */
    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    /**
     * @return DateTimeInterface|null
     */
    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->created_at;
    }

    /**
     * @param DateTimeInterface $created_at
     * @return $this
     */
    public function setCreatedAt(DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return DateTimeInterface|null
     */
    public function getUpdatedAt(): ?DateTimeInterface
    {
        return $this->updated_at;
    }

    /**
     * @param DateTimeInterface|null $updated_at
     * @return $this
     */
    public function setUpdatedAt(?DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|Task[]
     */
    public function getTasks(): Collection
    {
        return $this->tasks;
    }

    public function addTask(Task $task): self
    {
        if (!$this->tasks->contains($task)) {
            $this->tasks[] = $task;
            $task->setUser($this);
        }

        return $this;
    }

    public function removeTask(Task $task): self
    {
        if ($this->tasks->removeElement($task)) {
            // set the owning side to null (unless already changed)
            if ($task->getUser() === $this) {
                $task->setUser(null);
            }
        }

        return $this;
    }
}

templates/task/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Detalle tarea{% endblock %}

{% block body %}
    <!-- Flash Message add task success -->
    {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}
    <!-- Flash Message add task error -->
    {% for message in app.flashes('error') %}
        <div class="alert alert-warning">
            {{ message }}
        </div>
    {% endfor %}
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="card-box task-detail">
                        <div class="media mt-0 m-b-30">
                            <div class="media-body">
                                <h1 class="media-heading mb-0 mt-0">{{ task.title }}</h1>
                                {% if task.priority == 'HIGH' %}
                                    <strong>Prioridad: </strong><span class="badge badge-danger">Alta</span>
                                {% else %}
                                    <strong>Prioridad: </strong><span class="badge badge-success">Normal</span>
                                {% endif %}
                            </div>
                        </div>
                        <hr>
                        <h4 class="m-b-20">Responsable: {{ task.user.name }} {{ task.user.surname }}</h4>
                        <h5 class="m-b-20">Email: {{ task.user.email }}</h5>
                        <hr>
                        <h5 class="m-b-20">Descripción :</h5>
                        <p class="text-muted">
                            {{ task.content }}
                        </p>
                        <hr>
                        <ul class="list-inline task-dates m-b-0 mt-5">
                            <li>
                                <h5 class="m-b-5">Horas presupuestadas:</h5>
                                <p>{{ task.hours }} horas</p>
                            </li>
                            <li>
                                <h5 class="m-b-5">Fecha de inicio:</h5>
                                <p>{{ task.createdAt|date("d/m/Y")}}</p>
                            </li>
                            <li>
                                <h5 class="m-b-5">Fecha de Entrega:</h5>
                                <p>{{ task.deliveryDate|date("d/m/Y")}}</p>
                            </li>
                            <li>
                                <h5 class="m-b-5">Estado:</h5>
                                {%  if task.completed == 'YES' %}
                                    <span class="badge badge-success">Finalizada</span>
                                {% else %}
                                    <span class="badge badge-warning">En progreso...</span>
                                {% endif %}
                            </li>
                        </ul>
                        <hr>
                        <div class="clearfix"></div>
                        <div class="assign-team mt-4">
                            <h5 class="m-b-5">Assignada a:</h5>
                            <p>{{ task.user.name }} {{ task.user.surname }}</p>
                        </div>
                        <hr>
                        <div class="assign-team mt-4">
                            <a href="{{ path('tasks') }}">Volver a inicio</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end row -->
        </div>
        <!-- container -->
    </div>
{% endblock %}

templates/task/edit_task.html.twig
{% extends 'base.html.twig' %}

{% block title %}Todas las tareas{% endblock %}

{% block body %}
    <h1>Editar tarea:</h1>
    {{ form_start(taskForm) }}
    {{ form_row(taskForm.title) }}
    {{ form_row(taskForm.content) }}
    {{ form_row(taskForm.hours) }}
    {{ form_row(taskForm.priority) }}
    {{ form_row(taskForm.delivery_date) }}
    <button type="submit" class="btn">Guardar</button>
    {{ form_end(taskForm) }}

{% endblock %}

templates/task/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Todas las tareas{% endblock %}

{% block body %}
    <!-- Flash Message delete task success -->
    {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}
    {% if app.user %}
        {% set user_id = app.user.id %}
        {# dump(user_id) }} #}
    {% endif %}
    <h2>Lista de tareas.</h2>
    <hr>
    <div class="container mt-3">
        <h4>Buscar tarea:</h4>
        <input class="form-control" id="myInput" type="text" placeholder="Search..">
        <div class="add-task">
            <a href="{{ path('task_create') }}"><span class="material-icons add">add_box</span></a>
        </div>
        <br>
        {% if tasks %}
            <table class="table table-bordered table-hover">
                <thead class="thead-dark">
                <tr>
                    <th>#</th>
                    <th>TAREA</th>
                    <th>RESPONSABLE</th>
                    <th>HRS PRESUP</th>
                    <th>PRIORIDAD</th>
                    <th>ESTADO</th>
                    <th>FECHA DE ENTREGA</th>
                    <th>ACCIONES</th>
                </tr>
                </thead>
                <tbody id="myTable">
                 {% for task in tasks %}
                        <tr>
                            <td>{{ task.id }}</td>
                            <td>{{ task.title }}</td>
                            <td>{{ task.user.name }} {{ task.user.surname }}</td>
                            <td>{{ task.hours }}</td>
                            <td>
                                {% if task.priority == 'HIGH' %}
                                    {{ 'Alta' }}
                                {% elseif task.priority == 'NORMAL' %}
                                    {{ 'Normal' }}
                                {% else %}
                                    {{ 'Baja' }}
                                {% endif %}
                            </td>
                            <td>
                                {% if task.completed == 'YES' %}
                                    {{ 'Finalizada' }}
                                {% else %}
                                    {{ 'En progreso...' }}
                                {% endif %}
                            </td>
                            <td>{{ task.deliveryDate|date("d/m/Y") }}</td>
                            <td>
                                <a href="{{ path('task_detail', {'id':task.id}) }}" class="view" title="View" data-toggle="tooltip">
                                    <i class="material-icons view">&#xE417;</i>
                                </a>
                                {# Show only the creator of the task #}
                                {% if task.user.id == user_id  %}
                                    <a href="{{ path('task_edit', {'id':task.id}) }}" class="edit" title="Edit" data-toggle="tooltip">
                                        <i class="material-icons edit">&#xE254;</i>
                                    </a>
                                    <a href="{{ path('task_delete', {'id':task.id}) }}" class="delete" title="Delete" data-toggle="modal" data-target="#delete_task_Modal">
                                        <i class="material-icons delete">&#xE872;</i>
                                    </a>

                                    {#
                                    <!-- Button trigger modal -->
                                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#delete_task_Modal">
                                        Launch demo modal
                                    </button>

                                    <!-- Modal -->
                                    <div class="modal fade" id="delete_task_Modal" tabindex="-1" role="dialog" aria-labelledby="delete_task_ModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Eliminar {{ task.title }}</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <p>Estas seguro que deseas eliminar la tarea?</p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-danger Modal-delete" data-dismiss="modal">Cancelar</button>
                                                    <a href="{{ path('task_delete',{'id':task.id}) }}" class="btn btn-danger Modal-delete" data-dismiss="modal">Eliminar</a>
                                                    #}{# <button type="button" class="btn btn-primary Modal-delete">Eliminar</button> #}{#
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    #}
                               {% endif %}
                            </td>
                        </tr>
                 {% endfor %}
                </tbody>
            </table>
        {% else %}
            <strong> No hay ninguna tarea actualmente.</strong>
        {% endif %}
    </div>

    {#
    <!-- User login -->
    {% if app.user %}
        dump(app.user)
        <div class="mb-3">
            You are logged in as {{ app.user.username }},
            <a href="{{ path('logout') }}">Logout</a>
        </div>
    {% endif %}
    #}


{% endblock %}

templates/task/my_tasks.html.twig
{% extends 'base.html.twig' %}

{% block title %}Todas las tareas{% endblock %}

{% block body %}
    <!-- Flash Message register success -->
    {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}
    <h2>Mis tareas:</h2>
    <hr>
    <div class="container mt-3">
        <h4>Buscar tarea:</h4>
        <input class="form-control" id="myInput" type="text" placeholder="Search..">
        <div class="add-task">
            <a href="{{ path('task_create') }}"><span class="material-icons add">add_box</span></a>
        </div>
        <br>
        {% if tasks|length >= 1 %}
            <table class="table table-bordered table-hover">
                <thead class="thead-dark">
                <tr>
                    <th>#</th>
                    <th>TAREA</th>
                    <th>RESPONSABLE</th>
                    <th>HRS PRESUP</th>
                    <th>PRIORIDAD</th>
                    <th>ESTADO</th>
                    <th>FECHA DE ENTREGA</th>
                    <th>ACCIONES</th>
                </tr>
                </thead>
                <tbody id="myTable">
                {% for task in tasks %}
                    <tr>
                        <td>{{ task.id }}</td>
                        <td>{{ task.title }}</td>
                        <td>{{ task.user.name }} {{ task.user.surname }}</td>
                        <td>{{ task.hours }}</td>
                        <td>
                            {% if task.priority == 'HIGH' %}
                                {{ 'Alta' }}
                            {% elseif task.priority == 'NORMAL' %}
                                {{ 'Normal' }}
                            {% else %}
                                {{ 'Baja' }}
                            {% endif %}
                        </td>
                        <td>
                            {% if task.completed == 'YES' %}
                                {{ 'Finalizada' }}
                            {% else %}
                                {{ 'En progreso...' }}
                            {% endif %}
                        </td>
                        <td>{{ task.deliveryDate|date("d/m/Y") }}</td>
                        <td>
                            <a href="{{ path('task_detail',{'id':task.id}) }}" class="view" title="View"
                               data-toggle="tooltip">
                                <i class="material-icons view">&#xE417;</i>
                            </a>
                            <a href="{{ path('task_edit',{'id':task.id}) }}" class="edit" title="Edit"
                               data-toggle="tooltip">
                                <i class="material-icons edit">&#xE254;</i>
                            </a>
                            <a href="{{ path('task_delete',{'id':task.id}) }}" class="delete" title="Delete"
                               data-toggle="modal" data-target="#delete_task_Modal">
                                <i class="material-icons delete">&#xE872;</i>
                            </a>
                            <!-- Modal -->
                            <div class="modal fade" id="delete_task_Modal" tabindex="-1" role="dialog"
                                 aria-labelledby="delete_task_ModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">
                                                Eliminar {{ task.title }}</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <p>Estas seguro que deseas eliminar la tarea?</p>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-danger Modal-delete"
                                                    data-dismiss="modal">Cancelar
                                            </button>
                                            <a href="{{ path('task_delete'),{'id':task.id} }}"
                                               class="btn btn-danger Modal-delete" data-dismiss="modal">Eliminar</a>
                                            {# <button type="button" class="btn btn-primary Modal-delete">Eliminar</button> #}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        {% else %}
            <strong>No tienes tareas en este momento.</strong>
        {% endif %}
    </div>
{% endblock %}

templates/task/new_task.html.twig
{% extends 'base.html.twig' %}

{% block title %}TaskManager{% endblock %}

{% block body %}
    {% if edit is defined %}
        <h1>Editar tarea</h1>
    {% else %}
        <h1>Crear tarea</h1>
    {% endif %}
    {{ form_start(taskForm) }}
        {{ form_row(taskForm.title) }}
        {{ form_row(taskForm.content) }}
        {{ form_row(taskForm.hours) }}
        {{ form_row(taskForm.priority) }}
        {{ form_row(taskForm.delivery_date) }}
        <button type="submit" class="btn">Guardar</button>
    {{ form_end(taskForm) }}
{% endblock %}